version: '3'
services:
  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    restart: always
    ports:
     - "1700:80"
    environment:
     - JWT_ENABLED=false
    volumes:
     - './logs:/var/log/onlyoffice'
     - './data:/var/www/onlyoffice/Data'
     - './lib:/var/lib/onlyoffice'
     - './db:/var/lib/postgresql'