services:
  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "200:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data:rw
      - ./logs:/logs
    command:  redis-server /usr/local/etc/redis/redis.conf --requirepass "111111"
