version: '3.1'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 1100:80
    volumes:
      - ./html:/usr/share/nginx/html
      - ./logs:/var/log/nginx
