version: '3.1'
services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - 1100:80
    volumes:
      - /home/application/docker_nginx/conf.d/:/etc/nginx/conf.d
      - /home/application/docker_nginx/html:/usr/share/nginx/html
      - /home/application/docker_nginx/logs:/var/log/nginx