version: '3.3'
services:
  memos:
    image: 'neosmemo/memos:latest'
    container_name: memos
    ports:
      - '500:5230'
    volumes:
      - './memos:/var/opt/memos'
    command: --mode prod --port 5230
