version: '3.3'
services:
  memos:
    image: 'neosmemo/memos:latest'
    container_name: memos
    ports:
      - '5230:5230'
    volumes:
      - '/root/data/docker_data/memos/.memos/:/var/opt/memos'
    command: --mode prod --port 5230
