version: '3.3'
services:
  memos:
    image: 'neosmemo/memos:latest'
    container_name: memos
    hostname: memeos
    restart: always
    ports:
      - '500:5230'
    volumes:
      - './memos:/var/opt/memos'
