version: '3.7'
services:
  easyimage:
    image: ddsderek/easyimage:latest
    container_name: easyimage
    restart: always
    ports:
      - '8100:80'
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
