version: '3'
services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    privileged: true
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=111111
    volumes:
      - ./data/rabbitmq/rabbitmq/:/var/lib/rabbitmq
      - ./data/rabbitmq/rabbitmq/:/var/log/rabbitmq