version: '3'
services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    privileged: true
    ports:
      - "300:15672"
      - "301:5672"
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=111111
    volumes:
      - ./data/lib/rabbitmq/:/var/lib/rabbitmq
      - ./data/log/rabbitmq/:/var/log/rabbitmq
